//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf3_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificatee
    {
        public int numb_certificate { get; set; }
        public System.DateTime date_issue { get; set; }
        public decimal inn_departament_rsp { get; set; }
        public int product { get; set; }
        public decimal inn_company { get; set; }
        public string loginnbussinesmen { get; set; }
    
        public virtual company company { get; set; }
        public virtual rospotreb_departament rospotreb_departament { get; set; }
        public virtual userr userr { get; set; }
        public virtual product product1 { get; set; }
    }
}
